### ISSUE TITLE
Editor formatting toolbar has its text set to white while using a light theme

### ISSUE THREAD

**Issue by acovaci** [githrdw/vsc-home#10]
I know, outrageous :o. Who uses a light theme in 2024 😆.

Well, I do :) Seems that the buttons for the text editor are set to white:

<img width="641" alt="Screenshot 2024-07-10 at 16 26 15" src="https://github.com/githrdw/vsc-home/assets/6562353/1711c238-6f3f-4133-ab54-f8b3f79850f8">

P.S.: While we're at it, when the editor toolbar pops up, it also block shortcuts (at least on MacOS)

**Comment by githrdw** [comment]
Good catch! I will fix the toolbar button colors.

>P.S.: While we're at it, when the editor toolbar pops up, it also block shortcuts (at least on MacOS)

That's right, back then I was not able to support text editor shortcuts (CTRL+Z, CTRL+B) while also passing those shortcuts to VSCode.
I thought the chance that a VSCode shortcut would be needed while typing was small enough and decided to capture the shortcuts.

(funny thing is that just trying to reproduce this issue I tried to press F1 multiple times in the textbox which failed obviously xD)

**Comment by githrdw** [comment]
Fixed in latest release ✅
