### ISSUE TITLE
Improve instructions on how to add custom widget

### ISSUE THREAD

**Issue by apperside** [githrdw/vsc-home#4]
Hi,
I tried installing your extension because it seem cool, but I do not understand how to add custom widget.
In the docs you say:

> Go to %appdata%/vsc-home/widgets or similar

What does it mean? I am on a mac, which folder should I cd to? 

Thank you

**Comment by githrdw** [comment]
Hey, I think for MacOS the folder is located here:
```
/Users/<USER>/Library/Preferences/vsch-home/widgets
```

It is also possible to click the "Widgets" heading, which will open VS Code in the correct folder, where you can clone the template in.
Can you let me know if the path above works so I can add it to the docs?
