### ISSUE TITLE
Collection is not refreshing automatically

### ISSUE THREAD

**Issue by simryang** [githrdw/vsc-home#6]
Whenever I add item to Collection, I can't see anything.
After closing 'Home' tab and reopening it, I can see the result what I did above.
Please fix this.

**Comment by githrdw** [comment]
Thanks for reaching out and sorry for this late reply!
I had to find some time to fix this annoying bug and found that today.
You can manually install `v0.1.2` from https://github.com/githrdw/vsc-home/releases or wait until I have published the bugfix to the Marketplace.
