### ISSUE TITLE
simple way to embed an iframe

### ISSUE THREAD

**Issue by jimrandell** [githrdw/vsc-home#9]
thank you for your work on this, it might just be what i'm looking for.

I'm interested in simply displaying some iframes on the dashboard, without building anything. Can one simply edit the dashboard json file?
if it can be done (in anyway), can you give an example?

**Comment by githrdw** [comment]
Hi, that's a great idea!

I happened to try creating two iframes using the [template ](https://github.com/githrdw/vsch-template/tree/main) recently. The process is quite simple:

0. Install NodeJS (+ NPM)
1. Click on the "Widgets" title from the extension sidebar, which will open the widget folder
2. Clone the [vsch-template](https://github.com/githrdw/vsch-template/tree/main) into that directory as `vsch_Iframe` and `cd` into it.
3. Run `npm install`
4. Modify `src/Example.js`: 
  * Keep only the `import`, `export`, and `return` statements.
  * Remove all the variables in between.
6. Replace `<span>` with your `<iframe>`
7. Modify the `title` and `subtitle` in `package.json`
8. Run `npm build`
9. Refresh the widgets (e.g., press `CTRL + B` twice)

However, I encountered restrictions from instances over which I have no control.
Many services use the `X-Frame-Options: DENY` header to prevent loading content via an iframe. 
I also faced cookie permission issues myself, but don't let those words discourage you!

For now, the above steps are the fastest, but I will see if I can turn it into a user-friendly component later on.

**Comment by jimrandell** [comment]
hi, thank you for taking the time, i really appreciate it!

i'm sorry to say i could not get it to work.

starting with an iframe which works correctly when i test it in my own html, or use it in tools like grafana.

i was able to build successfully, but, after adding the the dashboard, the widget displays: `You just met a bug`
```
Widget debug information:
The following error occured attempting to load Demo #l
TypeError: Cannot read properties of undefined (reading 'default')
```

not sure how i should to do this, i did three builds:
- 1st try was just the iframe, 
- 2nd try with the iframe wrapped in a body tag,
- 3rd try with the body wrapped in an html tag

Perhaps i misunderstood your instructions. Here is what my example.js looks like (3rd try):

```js
import React, { useEffect, useState } from "react";
export default function Widget() {
  return (
    <html>
      <body>
        <iframe
          src="http://localhost:3000/public/question/87358f36-68b9-4b18-98b3-a9faa05122b3"
          frameborder="0"
          width="99%"
          height="99%"
          allowtransparency
        ></iframe>
      </body>
    </html>
  );
}
```

perhaps you might fork the example you were working with?

**Comment by githrdw** [comment]
I think that code should work. I feel you're almost there.
Could it be that the name of the template folder has changed after dragging the component to the grid?

Maybe you could remove the component, restart VS Code and drag the component again?

This error can occur if the grid can no longer find the component.

It may help to have dev tools open:
Press F1 (Command palette) > Webview developer tools

(by the way code wise the first and all other tries should work)

**Comment by githrdw** [comment]
Just to be sure; the vsch-home appdata directory should look something like this:

```.
├── layouts
│   ├── default.json
│   └── development.json
└── widgets
    └── vsch_Demo
        ├── LICENSE
        ├── dist
        │   ├── 287.js
        │   ├── 294.js
        │   ├── 294.js.LICENSE.txt
        │   ├── 976.js
        │   ├── 976.js.LICENSE.txt
        │   ├── main.js
        │   └── remoteEntry.js
        ├── package.json
        ├── src
        │   └── Example.js
        ├── webpack.config.js
        └── yarn.lock
```

**Comment by jimrandell** [comment]
- firstly, which version looks (almost) correct?
  - just the iframe? 
  - iframe inclosed in body tag? 
  - iframe and body enclosed in html tag?

```html
    <html>
      <body>
        <iframe
          src="http://localhost:3000/public/question/87358f36-68b9-4b18-98b3-a9faa05122b3"
          frameborder="0"
          width="99%"
          height="99%"
          allowtransparency
        ></iframe>
      </body>
    </html>
```

- i notice the `vsch-home` is spelled `vsc-home`:
  -  C:\Users\jimr\AppData\Roaming\vsc-home
  - i'll reinstall 
- on reinstall, it names the folder: vsc-home
  - C:\Users\jimr\AppData\Roaming\vsc-home
  - is that a bug?
- also, it did not create a layouts folder
  - i had to do it manually 
  - (i think it did that last time as well)

anyway, the reinstall produced the same results.

### **I 2nd my own suggestion, that you post the iframe version which works for you, as a separate repo.**

- and as long as i have my hand in the suggestion box, the demo should be included with the extension install in the first place   
  - as well as the iframe version
  - but, suppose you have your reasons!

Its awfully early in the states...or are you in the uk (as i am), or someplace else?

**Comment by jimrandell** [comment]
on reinstall, it names the folder: vsc-home
C:\Users\jimr\AppData\Roaming\vsc-home

is that a bug?

**Comment by githrdw** [comment]
Hi @jimrandell

* All versions looked correct to me, just-the-iframe one the most
* Good catch 😅 I see that in the docs and in my reply I said `vsch-home`, that is misspelled and should be `vsc-home`. 
I shall update the docs soon
* It should be `vsc-home`

Also, I have added the iframe feature as a built-in widget now.
After some testing I noticed that some websites use different zoom levels, so I implemented zooming functionalities.

You can download and install a beta prerelease of the extension here:
https://github.com/githrdw/vsc-home/releases/tag/vsch-core%400.1.3-beta.0

Please let me know what you think!
(oh and I am from the Netherlands btw ;)

**Comment by githrdw** [comment]
![image](https://github.com/githrdw/vsc-home/assets/1455140/618832a8-65e3-489e-80bf-ac7fa743138b)

This was my goal, to load some status pages :) 
Not really beautiful but it works
